parameters:
    recipe_finder_form: RecipeFinder\CoreBundle\Form\Type\RecipeFinderType
    recipe_finder_common_class_finder: RecipeFinder\CoreBundle\Common\Finder
    recipe_finder_common_class_fridge: RecipeFinder\CoreBundle\Common\Fridge

services:
    recipe_finder.form.type.task:
        class: %recipe_finder_form%
        tags:
            - { name: form.type, alias: recipe_finder }
    recipe_finder.common.finder:
        class: %recipe_finder_common_class_finder%
        arguments: [@jms_serializer, @recipe_finder.common.fridge, @validator]
    recipe_finder.common.fridge:
        class: %recipe_finder_common_class_fridge%
